import { createClient } from '@supabase/supabase-js'
const H={'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, x-caroline-key'}
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H})
const U=Deno.env.get('SUPABASE_URL')!,SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,RK=Deno.env.get('CAROLINE_RUNTIME_KEY'),db=createClient(U,SK)
const str=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null
const iso=(v:unknown)=>{const s=str(v);if(!s)return null;const d=new Date(s);return Number.isFinite(d.getTime())?d.toISOString():null}
const phone=(input:unknown)=>{const raw=String(input??'').trim(),d=raw.replace(/\D/g,'');if(!d)return null;let c:string;if(raw.startsWith('+'))c=`+${d}`;else if(d.length===10)c=`+1${d}`;else if(d.length===11&&d.startsWith('1'))c=`+${d}`;else c=`+${d}`;return /^\+[1-9]\d{7,14}$/.test(c)?c:null}
function runtimeOk(r:Request){return !!RK&&r.headers.get('x-caroline-key')===RK}
async function ownerChat(){const{data}=await db.from('caroline_integration_config').select('value').eq('key','telegram_owner_chat_id').maybeSingle();return str(data?.value)}
async function ownerOk(p:any){const owner=await ownerChat();return !!owner&&str(p?.owner_chat_id)===owner}
async function contactByPhone(p:unknown){const n=phone(p);if(!n)return null;const{data,error}=await db.from('contacts').select('id,normalized_phone,display_name,verification_status').eq('normalized_phone',n).maybeSingle();if(error)throw error;return data??null}
const rank:Record<string,number>={none:0,busy_only:1,title:2,details:3}
function ceiling(v:unknown){return v==='details'?'details':v==='title'?'title':'busy_only'}
function minLevel(a:'busy_only'|'title'|'details',b:'busy_only'|'title'|'details'){return rank[a]<=rank[b]?a:b}
function eventView(e:any,level:'busy_only'|'title'|'details'='details'){const base:any={id:e.id,start_at:e.start_at,end_at:e.end_at,status:e.status};if(level==='busy_only')return{...base,busy:true};if(level==='title')return{...base,title:e.title};return{...base,title:e.title,description:e.description,location:e.location,timezone:e.timezone,visibility:e.visibility,metadata:e.metadata}}
function sharedEventView(e:any,share:'busy_only'|'title'|'details'){const level=minLevel(share,ceiling(e.visibility));const base:any={start_at:e.start_at,end_at:e.end_at,busy:true};if(level==='title'||level==='details')base.title=e.title;if(level==='details'){base.description=e.description??null;base.location=e.location??null}return base}
async function effectiveShare(subjectId:string|null,viewerId:string|null){if(!viewerId)return 'none';let q=db.from('calendar_shares').select('share_level').eq('viewer_contact_id',viewerId);q=subjectId===null?q.is('subject_contact_id',null):q.eq('subject_contact_id',subjectId);const{data,error}=await q.maybeSingle();if(error)throw error;return(data?.share_level??'none') as 'none'|'busy_only'|'title'|'details'}
async function listEvents(ownerId:string|null,start:string,end:string,limit=50){let q=db.from('calendar_events').select('id,owner_contact_id,title,description,start_at,end_at,timezone,status,location,visibility,metadata').neq('status','cancelled').lt('start_at',end).gt('end_at',start).order('start_at',{ascending:true}).limit(Math.min(Math.max(limit,1),100));q=ownerId===null?q.is('owner_contact_id',null):q.eq('owner_contact_id',ownerId);const{data,error}=await q;if(error)throw error;return data??[]}
function mergeBusy(events:any[]){const x=events.map(e=>[Date.parse(e.start_at),Date.parse(e.end_at)] as [number,number]).filter(([a,b])=>Number.isFinite(a)&&Number.isFinite(b)&&b>a).sort((a,b)=>a[0]-b[0]);const out:[number,number][]=[];for(const[a,b]of x){const last=out[out.length-1];if(!last||a>last[1])out.push([a,b]);else last[1]=Math.max(last[1],b)}return out}
async function ownerList(p:any){if(!await ownerOk(p))return J({error:'unauthorized_owner'},403);const start=iso(p?.start_at)??new Date().toISOString(),end=iso(p?.end_at)??new Date(Date.now()+7*86400000).toISOString();if(Date.parse(end)<=Date.parse(start))return J({error:'invalid_window'},400);let ownerId:string|null=null;if(p?.phone){const c=await contactByPhone(p.phone);if(!c)return J({error:'contact_not_found'},404);ownerId=c.id}const events=await listEvents(ownerId,start,end,Number(p?.limit??50));return J({ok:true,start_at:start,end_at:end,events:events.map(e=>eventView(e,'details'))})}
async function current(p:any){if(!await ownerOk(p))return J({error:'unauthorized_owner'},403);const at=iso(p?.at)??new Date().toISOString();let ownerId:string|null=null;if(p?.phone){const c=await contactByPhone(p.phone);if(!c)return J({error:'contact_not_found'},404);ownerId=c.id}const end=new Date(Date.parse(at)+1).toISOString(),events=await listEvents(ownerId,at,end,10);return J({ok:true,at,current:events.map(e=>eventView(e,'details'))})}
async function openSlots(p:any){if(!await ownerOk(p))return J({error:'unauthorized_owner'},403);const start=iso(p?.start_at),end=iso(p?.end_at),mins=Math.max(1,Math.min(Number(p?.duration_minutes??30),1440));if(!start||!end||Date.parse(end)<=Date.parse(start))return J({error:'valid_start_at_and_end_at_required'},400);let ownerId:string|null=null;if(p?.phone){const c=await contactByPhone(p.phone);if(!c)return J({error:'contact_not_found'},404);ownerId=c.id}const events=await listEvents(ownerId,start,end,100),busy=mergeBusy(events),slots:any[]=[];let cur=Date.parse(start),stop=Date.parse(end),dur=mins*60000;for(const[a,b]of busy){if(a>cur&&a-cur>=dur)slots.push({start_at:new Date(cur).toISOString(),end_at:new Date(a).toISOString(),available_minutes:Math.floor((a-cur)/60000)});cur=Math.max(cur,b)}if(stop>cur&&stop-cur>=dur)slots.push({start_at:new Date(cur).toISOString(),end_at:new Date(stop).toISOString(),available_minutes:Math.floor((stop-cur)/60000)});return J({ok:true,start_at:start,end_at:end,duration_minutes:mins,slots:slots.slice(0,25)})}
async function createEvent(p:any){if(!await ownerOk(p))return J({error:'unauthorized_owner'},403);const title=str(p?.title),start=iso(p?.start_at),end=iso(p?.end_at);if(!title||!start||!end||Date.parse(end)<=Date.parse(start))return J({error:'title_and_valid_time_window_required'},400);let ownerId:string|null=null;if(p?.phone){const c=await contactByPhone(p.phone);if(!c)return J({error:'contact_not_found'},404);ownerId=c.id}const row={owner_contact_id:ownerId,title,description:str(p?.description),start_at:start,end_at:end,timezone:str(p?.timezone)??'America/New_York',status:['tentative','confirmed'].includes(p?.status)?p.status:'confirmed',location:str(p?.location),visibility:['private','busy_only','title','details'].includes(p?.visibility)?p.visibility:'private',source:'supabase_native',created_by:'telegram_owner',metadata:p?.metadata&&typeof p.metadata==='object'?p.metadata:{}};const{data,error}=await db.from('calendar_events').insert(row).select('id,owner_contact_id,title,description,start_at,end_at,timezone,status,location,visibility,created_at').single();if(error)return J({error:'calendar_persistence_failed'},500);return J({ok:true,event:data},201)}
async function cancelEvent(p:any){if(!await ownerOk(p))return J({error:'unauthorized_owner'},403);const id=str(p?.event_id);if(!id)return J({error:'event_id_required'},400);const{data,error}=await db.from('calendar_events').update({status:'cancelled'}).eq('id',id).neq('status','cancelled').select('id,title,start_at,end_at,status').maybeSingle();if(error)return J({error:'calendar_persistence_failed'},500);if(!data)return J({error:'event_not_found_or_already_cancelled'},404);return J({ok:true,event:data})}
async function setShare(p:any){if(!await ownerOk(p))return J({error:'unauthorized_owner'},403);const level=['none','busy_only','title','details'].includes(p?.share_level)?p.share_level:null;if(!level)return J({error:'invalid_share_level'},400);const viewer=await contactByPhone(p?.viewer_phone);if(!viewer)return J({error:'viewer_contact_not_found'},404);let subjectId:string|null=null;if(p?.subject_phone){const subject=await contactByPhone(p.subject_phone);if(!subject)return J({error:'subject_contact_not_found'},404);subjectId=subject.id}let q=db.from('calendar_shares').select('id').eq('viewer_contact_id',viewer.id);q=subjectId===null?q.is('subject_contact_id',null):q.eq('subject_contact_id',subjectId);const{data:existing}=await q.maybeSingle();const payload={subject_contact_id:subjectId,viewer_contact_id:viewer.id,share_level:level,notes:str(p?.notes),created_by:'telegram_owner'};const result=existing?await db.from('calendar_shares').update(payload).eq('id',existing.id).select('id,subject_contact_id,viewer_contact_id,share_level,notes').single():await db.from('calendar_shares').insert(payload).select('id,subject_contact_id,viewer_contact_id,share_level,notes').single();if(result.error)return J({error:'calendar_share_persistence_failed'},500);return J({ok:true,share:result.data})}
async function sharedSchedule(p:any){const viewer=await contactByPhone(p?.viewer_phone);if(!viewer||viewer.verification_status!=='verified')return J({error:'not_authorized'},403);let subjectId:string|null=null;if(p?.subject_phone){const subject=await contactByPhone(p.subject_phone);if(!subject)return J({error:'subject_contact_not_found'},404);subjectId=subject.id}const level=await effectiveShare(subjectId,viewer.id);if(level==='none')return J({ok:true,share_level:'none',events:[]});const start=iso(p?.start_at)??new Date().toISOString(),end=iso(p?.end_at)??new Date(Date.now()+86400000).toISOString();if(Date.parse(end)<=Date.parse(start))return J({error:'invalid_window'},400);const events=await listEvents(subjectId,start,end,25),share=level as 'busy_only'|'title'|'details';return J({ok:true,share_level:level,start_at:start,end_at:end,events:events.map(e=>sharedEventView(e,share))})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(!runtimeOk(req))return J({error:'unauthorized'},401);if(req.method!=='POST')return J({error:'method_not_allowed'},405);try{const p=await req.json(),path=new URL(req.url).pathname;if(path.endsWith('/list'))return await ownerList(p);if(path.endsWith('/current'))return await current(p);if(path.endsWith('/open-slots'))return await openSlots(p);if(path.endsWith('/create'))return await createEvent(p);if(path.endsWith('/cancel'))return await cancelEvent(p);if(path.endsWith('/share-set'))return await setShare(p);if(path.endsWith('/shared-schedule'))return await sharedSchedule(p);return J({error:'not_found'},404)}catch(e){console.error(JSON.stringify({service:'caroline-calendar',event:'request_failed',message:e instanceof Error?e.message:'unknown'}));return J({error:'internal_error'},500)}})

