import { createClient } from '@supabase/supabase-js'
const H={'Content-Type':'application/json','Cache-Control':'no-store'}
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H})
const U=Deno.env.get('SUPABASE_URL')!,SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,RK=Deno.env.get('CAROLINE_RUNTIME_KEY'),db=createClient(U,SK)
const str=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null
async function cfg(k:string){const{data}=await db.from('caroline_integration_config').select('value').eq('key',k).maybeSingle();return str(data?.value)}
function phone(v:unknown){const r=str(v);if(!r)return null;const d=r.replace(/\D/g,'');let c='';if(r.startsWith('+'))c=`+${d}`;else if(d.length===10)c=`+1${d}`;else if(d.length===11&&d.startsWith('1'))c=`+${d}`;else c=`+${d}`;return /^\+[1-9]\d{7,14}$/.test(c)?c:null}
async function ownerPhones(){const multi=await cfg('owner_phone_numbers');const out=new Set<string>();if(multi){try{const a=JSON.parse(multi);if(Array.isArray(a))for(const v of a){const n=phone(v);if(n)out.add(n)}}catch{}}const legacy=phone(await cfg('owner_phone_number'));if(legacy)out.add(legacy);return out}
Deno.serve(async r=>{if(!RK||r.headers.get('x-caroline-key')!==RK)return J({error:'unauthorized'},401);if(r.method!=='POST')return J({error:'method_not_allowed'},405);let p:any={};try{p=await r.json()}catch{return J({error:'invalid_json'},400)};const internal=p?.internal_phone_lookup===true;const[expected,owners]=await Promise.all([cfg('telegram_owner_chat_id'),ownerPhones()]);const suppliedOwner=phone(p?.owner_phone);const ownerAuthorized=(!!expected&&str(p?.owner_chat_id)===expected)||(!!suppliedOwner&&owners.has(suppliedOwner));if(!internal&&!ownerAuthorized)return J({error:'unauthorized_owner'},403);const ph=phone(p?.phone),name=str(p?.name);if(internal&&!ph)return J({error:'phone_required_for_internal_lookup'},400);if(ph){const{data,error}=await db.from('contacts').select('id,display_name,first_name,last_name,normalized_phone,relationship_to_owner,contact_type,verification_status,tone_profile').eq('normalized_phone',ph).limit(5);if(error)return J({error:'contact_lookup_failed'},500);return J({ok:true,match_count:(data??[]).length,candidates:data??[]})}if(!name)return J({error:'name_or_phone_required'},400);const safe=name.replace(/[%_]/g,'');const{data,error}=await db.from('contacts').select('id,display_name,first_name,last_name,normalized_phone,relationship_to_owner,contact_type,verification_status,tone_profile').or(`display_name.ilike.%${safe}%,first_name.ilike.%${safe}%,last_name.ilike.%${safe}%`).order('updated_at',{ascending:false}).limit(10);if(error)return J({error:'contact_lookup_failed'},500);const rows=data??[];return J({ok:true,match_count:rows.length,unique:rows.length===1,candidates:rows})})

