import { createClient } from '@supabase/supabase-js'
const H={'Content-Type':'application/json','Cache-Control':'no-store'}
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H})
const U=Deno.env.get('SUPABASE_URL')!,SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,RK=Deno.env.get('CAROLINE_RUNTIME_KEY'),db=createClient(U,SK)
const str=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null
Deno.serve(async r=>{if(!RK||r.headers.get('x-caroline-key')!==RK)return J({error:'unauthorized'},401);if(r.method!=='POST')return J({error:'method_not_allowed'},405);let p:any={};try{p=await r.json()}catch{return J({error:'invalid_json'},400)};const conversationId=str(p?.conversation_id);if(!conversationId)return J({error:'conversation_id_required'},400);const{data:call,error}=await db.from('call_history').select('id,contact_id,conversation_id,relationship_context_and_notes,request_summary,started_at').eq('conversation_id',conversationId).maybeSingle();if(error||!call)return J({error:'call_history_not_found'},404);let scheduledId=str(p?.scheduled_action_id);if(!scheduledId){const{data:match}=await db.from('scheduled_actions').select('id').eq('conversation_id',conversationId).in('status',['reserved','executing','scheduled']).order('created_at',{ascending:false}).limit(1).maybeSingle();scheduledId=match?.id??null}let scheduled:any=null;if(scheduledId){const{data}=await db.from('scheduled_actions').update({status:'completed',completed_at:new Date().toISOString(),conversation_id:conversationId,call_history_id:call.id,last_error:null}).eq('id',scheduledId).in('status',['reserved','executing','scheduled']).select('id,status,calendar_event_id,project_id,target_contact_id').maybeSingle();scheduled=data??null}
let candidateMemory:any=null;const note=str(call.relationship_context_and_notes);if(note&&call.contact_id){const{data:prior}=await db.from('memory_items').select('id').eq('source_call_history_id',call.id).eq('memory_type','context_note').maybeSingle();if(!prior){const{data}=await db.from('memory_items').insert({subject_contact_id:call.contact_id,project_id:scheduled?.project_id??null,memory_type:'context_note',content:note,status:'candidate',authority:'observed',confidence:0.65,source_kind:'phone_call',source_conversation_id:conversationId,source_call_history_id:call.id,observed_at:call.started_at??new Date().toISOString(),metadata:{generated_from:'relationship_context_and_notes'}}).select('id,memory_type,content,status,authority,confidence').single();candidateMemory=data??null}}
return J({ok:true,call_history_id:call.id,scheduled_action:scheduled,candidate_memory:candidateMemory})})

