import { createClient } from '@supabase/supabase-js'
const headers={'Content-Type':'application/json','Cache-Control':'no-store'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers})
const supabaseUrl=Deno.env.get('SUPABASE_URL')!,serviceRoleKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,runtimeKey=Deno.env.get('CAROLINE_RUNTIME_KEY'),telegramBotToken=Deno.env.get('TELEGRAM_BOT_TOKEN')
const db=createClient(supabaseUrl,serviceRoleKey),RETRY_DELAYS_MS=[0,1000,5000]
function authorized(req:Request){return !!runtimeKey&&req.headers.get('x-caroline-key')===runtimeKey}
function log(event:string,fields:Record<string,unknown>={}){console.log(JSON.stringify({service:'caroline-notify',event,...fields}))}
function clean(value:unknown,fallback='—'){if(typeof value!=='string')return fallback;const t=value.trim();return t||fallback}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms))
async function telegramChatId(){const{data}=await db.from('caroline_integration_config').select('value').eq('key','telegram_owner_chat_id').maybeSingle();return typeof data?.value==='string'&&data.value.trim()?data.value.trim():null}
function formatCallBrief(call:any){const caller=clean(call?.caller_name,clean(call?.normalized_phone,'Unknown caller'));return ['📞 Caroline call brief',`Caller: ${caller}`,`Provider: ${clean(call?.telephony_provider,'unknown')}`,`Direction: ${clean(call?.direction,'unknown')}`,`Outcome: ${clean(call?.call_outcome,'not classified')}`,`Urgency: ${clean(call?.request_urgency,'not classified')}`,`Summary: ${clean(call?.request_summary,'No summary available')}`,`Callback: ${clean(call?.callback_number,'none provided')}`,`Conversation: ${clean(call?.conversation_id,'unavailable')}`].join('\n').slice(0,4000)}
function formatEventBrief(event:any){const d=event?.details??{};if(event?.event_type==='sms_delivered')return ['✅ Caroline text delivered',`To: ${clean(d?.normalized_phone,'unavailable')}`,`Delivered at: ${clean(d?.delivered_at,'unknown')}`,`Message ID: ${clean(d?.provider_message_id,'unavailable')}`].join('\n').slice(0,4000);if(event?.event_type==='phone_admission_attempt'){const n=clean(d?.normalized_phone,'unavailable'),state=clean(d?.admission_state,'unknown');return ['🛡️ Caroline phone admission',`Number: ${n}`,`State: ${state}`,`Reason: ${clean(d?.failure_reason,'not provided')}`,'Owner actions:',`• allow calls from ${n}`,`• restrict ${n}`,`• ban ${n} permanently`].join('\n').slice(0,4000)}const restricted=event?.event_type==='restricted_call_attempt';return [(restricted?'🚫 Restricted call attempt':'⚠️ Caroline event'),`Event: ${clean(event?.event_type,'unknown')}`,`Caller: ${clean(d?.normalized_phone,'unavailable')}`,`Reason: ${clean(d?.failure_reason,'not provided')}`,`Provider: ${clean(d?.telephony_type,'unknown')}`,`Direction: ${clean(d?.direction,'unknown')}`,`Call ID: ${clean(d?.provider_call_id,'unavailable')}`,`Conversation: ${clean(event?.conversation_id,'unavailable')}`].join('\n').slice(0,4000)}
function formatSmsBrief(sms:any,kind:string){const who=clean(sms?.contacts?.display_name,clean(sms?.normalized_phone,'Unknown'));if(kind==='sent')return ['📤 Caroline text sent',`To: ${who}`,`Sent at: ${clean(sms?.sent_at,'unknown')}`,`Message: ${clean(sms?.body,'')}`].join('\n').slice(0,4000);return ['📩 Caroline inbound text',`From: ${who}`,`Received: ${clean(sms?.created_at,'unknown')}`,`Message: ${clean(sms?.body,'')}`].join('\n').slice(0,4000)}
async function telegramSendOnce(text:string){const chatId=await telegramChatId();if(!telegramBotToken||!chatId)return{ok:false,status:503,error:'telegram_not_configured',retryable:false,retryAfterMs:0};try{const response=await fetch(`https://api.telegram.org/bot${telegramBotToken}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,text})});let body:any=null;try{body=await response.json()}catch{}if(!response.ok||body?.ok!==true){const error=typeof body?.description==='string'?body.description.slice(0,500):`telegram_http_${response.status}`,secs=Number(body?.parameters?.retry_after),retryAfterMs=Number.isFinite(secs)&&secs>0?Math.min(secs*1000,30000):0,retryable=response.status===408||response.status===429||response.status>=500;return{ok:false,status:response.status,error,retryable,retryAfterMs}}return{ok:true,status:response.status,message_id:body?.result?.message_id??null}}catch{return{ok:false,status:502,error:'telegram_request_failed',retryable:true,retryAfterMs:0}}}
async function sendWithRetry(text:string,base:number,record:(n:number)=>Promise<void>){let last:any=null;for(let i=0;i<RETRY_DELAYS_MS.length;i++){if(i>0)await sleep(Math.max(RETRY_DELAYS_MS[i],Number(last?.retryAfterMs??0)));await record(base+i+1);const r:any=await telegramSendOnce(text);if(r.ok)return{...r,attempts_used:i+1};last=r;if(!r.retryable)break}return{...(last??{status:502,error:'telegram_send_failed'}),ok:false}}
Deno.serve(async req=>{if(!authorized(req))return json({error:'unauthorized'},401);if(req.method!=='POST')return json({error:'method_not_allowed'},405);let body:any;try{body=await req.json()}catch{return json({error:'invalid_json'},400)}const callHistoryId=typeof body?.call_history_id==='string'?body.call_history_id.trim():'',conversationId=typeof body?.conversation_id==='string'?body.conversation_id.trim():'',eventId=typeof body?.event_id==='string'?body.event_id.trim():'',smsHistoryId=typeof body?.sms_history_id==='string'?body.sms_history_id.trim():'',notificationKind=typeof body?.notification_kind==='string'?body.notification_kind.trim():'inbound';if(!callHistoryId&&!conversationId&&!eventId&&!smsHistoryId)return json({error:'notification_target_required'},400)
if(smsHistoryId){const{data:sms,error:readError}=await db.from('sms_history').select('*,contacts:contact_id(display_name,normalized_phone)').eq('id',smsHistoryId).maybeSingle();if(readError)return json({error:'notification_lookup_failed'},500);if(!sms)return json({error:'sms_history_not_found'},404);if(sms.telegram_notification_status==='sent'&&sms.telegram_message_id)return json({ok:true,sent:true,duplicate:true,message_id:sms.telegram_message_id});const sent:any=await sendWithRetry(formatSmsBrief(sms,notificationKind),0,async()=>{});if(!sent.ok){await db.from('sms_history').update({telegram_notification_status:sent.error==='telegram_not_configured'?'pending':'failed'}).eq('id',smsHistoryId);return json({error:sent.error},sent.status===503?503:502)}await db.from('sms_history').update({telegram_notification_status:'sent',telegram_message_id:sent.message_id,telegram_notified_at:new Date().toISOString()}).eq('id',smsHistoryId);return json({ok:true,sent:true,duplicate:false,message_id:sent.message_id})}
if(eventId&&!callHistoryId){const{data:event,error:readError}=await db.from('events_processed').select('*').eq('event_id',eventId).maybeSingle();if(readError)return json({error:'notification_lookup_failed'},500);if(!event)return json({error:'event_not_found'},404);if(event.telegram_notification_status==='sent'&&event.telegram_message_id)return json({ok:true,sent:true,duplicate:true,message_id:event.telegram_message_id});const base=Number(event.telegram_notification_attempts??0),sent:any=await sendWithRetry(formatEventBrief(event),base,async attempts=>{await db.from('events_processed').update({telegram_notification_attempts:attempts}).eq('event_id',eventId)});if(!sent.ok){await db.from('events_processed').update({telegram_notification_status:sent.error==='telegram_not_configured'?'pending':'failed',telegram_notification_error:sent.error}).eq('event_id',eventId);return json({error:sent.error},sent.status===503?503:502)}await db.from('events_processed').update({telegram_notification_status:'sent',telegram_message_id:sent.message_id,telegram_notified_at:new Date().toISOString(),telegram_notification_error:null}).eq('event_id',eventId);return json({ok:true,sent:true,duplicate:false,message_id:sent.message_id})}
let query=db.from('call_history').select('*');query=callHistoryId?query.eq('id',callHistoryId):query.eq('conversation_id',conversationId);const{data:call,error:readError}=await query.maybeSingle();if(readError)return json({error:'notification_lookup_failed'},500);if(!call)return json({error:'call_history_not_found'},404);if(call.telegram_notification_status==='skipped')return json({ok:true,sent:false,skipped:true,reason:'notification_skipped_by_call_state'});if(call.telegram_notification_status==='sent'&&call.telegram_message_id)return json({ok:true,sent:true,duplicate:true,message_id:call.telegram_message_id});const base=Number(call.telegram_notification_attempts??0),sent:any=await sendWithRetry(formatCallBrief(call),base,async attempts=>{await db.from('call_history').update({telegram_notification_attempts:attempts}).eq('id',call.id)});if(!sent.ok){await db.from('call_history').update({telegram_notification_status:sent.error==='telegram_not_configured'?'pending':'failed',telegram_notification_error:sent.error}).eq('id',call.id);return json({error:sent.error},sent.status===503?503:502)}const{error:updateError}=await db.from('call_history').update({telegram_notification_status:'sent',telegram_message_id:sent.message_id,telegram_notified_at:new Date().toISOString(),telegram_notification_error:null}).eq('id',call.id);return json({ok:true,sent:true,state_recorded:!updateError,duplicate:false,message_id:sent.message_id})})

