import { createClient } from '@supabase/supabase-js'
const U=Deno.env.get('SUPABASE_URL')!,SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,RK=Deno.env.get('CAROLINE_RUNTIME_KEY'),db=createClient(U,SK)
const H={'Content-Type':'application/json','Cache-Control':'no-store'},J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H})
const str=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null
function phone(v:unknown){const r=str(v);if(!r)return null;const d=r.replace(/\D/g,'');let c='';if(r.startsWith('+'))c='+'+d;else if(d.length===10)c='+1'+d;else if(d.length===11&&d.startsWith('1'))c='+'+d;else c='+'+d;return /^\+[1-9]\d{7,14}$/.test(c)?c:null}
function iso(v:unknown){const s=str(v);if(!s)return null;const d=new Date(s);return Number.isNaN(d.getTime())?null:d.toISOString()}
async function cfg(k:string){const{data}=await db.from('caroline_integration_config').select('value').eq('key',k).maybeSingle();return str(data?.value)}
async function ownerPhones(){const out=new Set<string>();const multi=await cfg('owner_phone_numbers');if(multi){try{const a=JSON.parse(multi);if(Array.isArray(a))for(const v of a){const n=phone(v);if(n)out.add(n)}}catch{}}const legacy=phone(await cfg('owner_phone_number'));if(legacy)out.add(legacy);return out}
function auth(r:Request){return !!RK&&r.headers.get('x-caroline-key')===RK}
async function ownerOk(p:any){const[chat,owners]=await Promise.all([cfg('telegram_owner_chat_id'),ownerPhones()]);const supplied=phone(p?.owner_phone);return (!!chat&&str(p?.owner_chat_id)===chat)||(!!supplied&&owners.has(supplied))}
Deno.serve(async r=>{if(!auth(r))return J({error:'unauthorized'},401);if(r.method!=='POST')return J({error:'method_not_allowed'},405);let p:any={};try{p=await r.json()}catch{return J({error:'invalid_json'},400)};if(!await ownerOk(p))return J({error:'unauthorized_owner'},403);const path=new URL(r.url).pathname;if(!path.endsWith('/schedule'))return J({error:'not_found'},404)
const requestId=str(p?.request_id)??(str(p?.conversation_id)&&Number.isFinite(Number(p?.agent_turn))?str(p.conversation_id)+':'+String(Number(p.agent_turn)):null),executeAt=iso(p?.execute_at),targetPhone=phone(p?.target_phone),summary=str(p?.message_summary);if(!requestId||!executeAt||!targetPhone||!summary)return J({error:'request_identity_execute_at_target_phone_message_summary_required'},400);if(Date.parse(executeAt)<=Date.now()-60000)return J({error:'execute_at_in_past'},400)
const{data:contact}=await db.from('contacts').select('id,display_name,normalized_phone').eq('normalized_phone',targetPhone).maybeSingle();if(!contact)return J({error:'target_contact_not_found'},404)
const idem='owner:schedule_sms:'+requestId;const{data:prior}=await db.from('scheduled_actions').select('*').eq('idempotency_key',idem).maybeSingle();if(prior)return J({ok:true,duplicate:true,scheduled_action:prior})
const linked=str(p?.linked_call_history_id);if(linked){const{data:call}=await db.from('call_history').select('id,normalized_phone').eq('id',linked).maybeSingle();if(!call||call.normalized_phone!==targetPhone)return J({error:'linked_call_mismatch'},409)}
const tz=str(p?.timezone)??'America/New_York';const endAt=new Date(Date.parse(executeAt)+5*60000).toISOString();const{data:event,error:ee}=await db.from('calendar_events').insert({title:'Text '+contact.display_name,description:summary,start_at:executeAt,end_at:endAt,timezone:tz,status:'confirmed',visibility:'private',source:'supabase_native',created_by:'owner',metadata:{kind:'scheduled_action',action_type:'outbound_sms',target_contact_id:contact.id}}).select('id,title,start_at,end_at,timezone,status').single();if(ee)return J({error:'calendar_persistence_failed'},500)
const row={calendar_event_id:event.id,target_contact_id:contact.id,action_type:'outbound_sms',execute_at:executeAt,timezone:tz,status:'scheduled',purpose:summary,original_instruction:str(p?.original_instruction),idempotency_key:idem,created_by:str(p?.owner_chat_id)?'telegram_owner':'voice_owner',metadata:{target_name:contact.display_name,sms_message_summary:summary,linked_call_history_id:linked}};const{data:action,error}=await db.from('scheduled_actions').insert(row).select('*').single();if(error){await db.from('calendar_events').delete().eq('id',event.id);return J({error:'scheduled_action_persistence_failed'},500)}return J({ok:true,duplicate:false,calendar_event:event,scheduled_action:action,target:{id:contact.id,display_name:contact.display_name}},201)})

