const headers={'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, x-caroline-key'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers})
const OWNER_PHONE_TOOL_IDS=["tool_7101m2trb905eg48rncavzaf10r7","tool_3901m2trbk75e9z8hjb3t5p8pezz"],NON_OWNER_PHONE_TOOL_IDS=["tool_9001m2rea06tepm9sbb47g30zn81","tool_3201m2s016syeternw1h0m67mhg7","tool_6801m2s01ynyeg29sa89nmew54v7"]
const runtimeKey=Deno.env.get('CAROLINE_RUNTIME_KEY'),supabaseUrl=Deno.env.get('SUPABASE_URL')!,contextServiceUrl=`${supabaseUrl}/functions/v1/caroline-context/caller`,callAccessAttemptUrl=`${supabaseUrl}/functions/v1/caroline-call-access/record-restricted-attempt`,consumeReentryUrl=`${supabaseUrl}/functions/v1/caroline-call-access/consume-reentry`,phoneAdmissionAttemptUrl=`${supabaseUrl}/functions/v1/caroline-phone-admission/record-attempt`
function authorized(req:Request){return !!runtimeKey&&req.headers.get('x-caroline-key')===runtimeKey}
function callerIdFromPayload(payload:any){const value=payload?.caller_id??payload?.data?.caller_id??null;return typeof value==='string'&&value.trim()?value.trim():null}
function log(event:string,fields:Record<string,unknown>={}){console.log(JSON.stringify({service:'caroline-context-init',event,...fields}))}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers});const authOk=authorized(req);log('request_received',{method:req.method,has_auth_header:!!req.headers.get('x-caroline-key'),auth_ok:authOk,runtime_key_configured:!!runtimeKey});if(!authOk)return json({error:'unauthorized'},401);if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const payload=await req.json(),callerId=callerIdFromPayload(payload),conversationId=payload?.conversation_id??payload?.data?.conversation_id??null;if(!callerId)return json({error:'caller_id_required'},400);const response=await fetch(contextServiceUrl,{method:'POST',headers:{'Content-Type':'application/json','x-caroline-key':runtimeKey!},body:JSON.stringify({phone:callerId})});if(!response.ok)return json({error:'context_service_error'},502);const context=await response.json(),cal=context.calendar??{},ca=context.call_answering??{status:'allowed',reentry_notice_pending:false};
let firstMessage:string|null=null,reentryPending=ca.reentry_notice_pending===true
if(ca.status==='restricted'&&runtimeKey){EdgeRuntime.waitUntil(fetch(callAccessAttemptUrl,{method:'POST',headers:{'Content-Type':'application/json','x-caroline-key':runtimeKey},body:JSON.stringify({phone:callerId,conversation_id:conversationId})}).catch(()=>{log('restricted_attempt_record_failed',{conversation_id:conversationId})}));firstMessage="Chris hasn't re-authorized calls from this number yet. I've let him know you called. Have a good day."
}else if(['waitlisted','restricted_by_owner','banned'].includes(ca.status)&&runtimeKey){EdgeRuntime.waitUntil(fetch(phoneAdmissionAttemptUrl,{method:'POST',headers:{'Content-Type':'application/json','x-caroline-key':runtimeKey},body:JSON.stringify({phone:callerId,conversation_id:conversationId,admission_state:ca.status,reason:ca.reason_summary??null})}).catch(()=>{log('phone_admission_attempt_record_failed',{conversation_id:conversationId,status:ca.status})}));firstMessage=ca.status==='waitlisted'?"This number isn't currently authorized to use Caroline. Chris has been notified. Have a good day.":ca.status==='banned'?"This number is not authorized to use Caroline. Chris has been notified. Have a good day.":"Calls from this number are currently paused pending Chris's review. He has been notified. Have a good day."
}else if(ca.status==='allowed'&&reentryPending&&runtimeKey){try{const consume=await fetch(consumeReentryUrl,{method:'POST',headers:{'Content-Type':'application/json','x-caroline-key':runtimeKey},body:JSON.stringify({phone:callerId})});if(consume.ok){reentryPending=false;firstMessage="Before we get into it, I hope we don't have a repeat of our last interaction. It was unfortunate. I'm glad we're able to speak again."}else log('reentry_consume_failed',{conversation_id:conversationId,status:consume.status})}catch{log('reentry_consume_failed',{conversation_id:conversationId,status:'request_failed'})}}
let contextJson=context.caroline_context_json??''
if(contextJson&&reentryPending!==ca.reentry_notice_pending){try{const parsed=JSON.parse(contextJson);parsed.call_answering={...(parsed.call_answering??{}),reentry_notice_pending:reentryPending};contextJson=JSON.stringify(parsed)}catch{}}
const isOwner=context.caller_identity_status==='verified_owner'||context.access_tier==='tier_owner',blocked=['restricted','waitlisted','restricted_by_owner','banned'].includes(ca.status),phoneToolIds=blocked?[]:(isOwner?OWNER_PHONE_TOOL_IDS:NON_OWNER_PHONE_TOOL_IDS)
const body:any={type:'conversation_initiation_client_data',dynamic_variables:{caroline_context_json:contextJson,caller_access_tier:context.access_tier??'tier_0_unknown_unverified',caller_tone_profile:context.tone_profile??'professional',caller_identity_status:context.caller_identity_status??'unknown',caller_relationship_context:context.relationship_context==null?'':JSON.stringify(context.relationship_context),caller_permissions_json:JSON.stringify(context.permissions??{}),caller_recent_history:JSON.stringify(context.recent_history??[]),caroline_active_instructions:JSON.stringify(context.active_instructions??[]),availability_status:context.availability?.human_readable??'',caller_persona_profile_json:JSON.stringify(context.persona_profile??null),session_energy:context.session_energy??'neutral',call_answering_status:ca.status??'allowed',call_answering_reason:ca.reason_summary??'',call_reentry_notice_pending:reentryPending?'true':'false',calendar_share_level:cal.share_level??'none',calendar_current_activity:JSON.stringify(cal.current_activity??null),calendar_next_event:JSON.stringify(cal.next_event??null),outbound_call_brief_json:'{}'},conversation_config_override:{agent:{prompt:{tool_ids:phoneToolIds}}}}
if(firstMessage)body.conversation_config_override.agent.first_message=firstMessage;const encoded=JSON.stringify(body);if(new TextEncoder().encode(encoded).byteLength>262144)return json({error:'response_too_large'},500);log('context_returned',{conversation_id:conversationId,caller_identity_status:context.caller_identity_status??'unknown',calendar_share_level:cal.share_level??'none',call_answering_status:ca.status??'allowed',reentry_notice_pending:reentryPending,first_message_overridden:!!firstMessage,owner_tool_scope:isOwner,tool_count:phoneToolIds.length,sms_tools_exposed:isOwner&&!blocked,blocked_tool_scope:blocked,least_privilege_phone_scope:!isOwner&&!blocked});return new Response(encoded,{status:200,headers})}catch{return json({error:'invalid_request'},400)}})

