import assert from 'node:assert/strict'
import test from 'node:test'
import { handleTwilioWebhook } from '../src/handlers/twilio.ts'
import { expectedTwilioSignature, verifyTwilioRequest } from '../src/lib/twilio-security.ts'
const token='12345'
test('matches Twilio official HMAC-SHA1 form vector',async()=>{const url='https://example.com/myapp.php?foo=1&bar=2'; const sig=await expectedTwilioSignature(token,url,{CallSid:'CA1234567890ABCDE',Caller:'+14158675310',Digits:'1234',From:'+14158675310',To:'+18005551212'}); assert.equal(sig,'L/OH5YylLD5NRKLltdqwSvS0BnU=')})
test('verifies exact incoming URL and form params',async()=>{const url='https://voice.example.com/webhook/twilio/voice?foo=bar'; const raw='CallSid=CA123&From=%2B15550000000'; const sig=await expectedTwilioSignature(token,url,{CallSid:'CA123',From:'+15550000000'}); const req=new Request(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Twilio-Signature':sig},body:raw}); assert.equal(await verifyTwilioRequest(req,raw,token),true)})
test('rejects signature for a different public URL',async()=>{const raw='CallSid=CA123'; const sig=await expectedTwilioSignature(token,'https://other.example.com/webhook/twilio/voice',{CallSid:'CA123'}); const req=new Request('https://voice.example.com/webhook/twilio/voice',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Twilio-Signature':sig},body:raw}); assert.equal(await verifyTwilioRequest(req,raw,token),false)})
test('verifies JSON bodySHA256',async()=>{const raw='{"CallSid":"CA123"}'; const digest=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw))); const hash=Array.from(digest,b=>b.toString(16).padStart(2,'0')).join(''); const url=`https://voice.example.com/webhook/twilio/status?bodySHA256=${hash}`; const sig=await expectedTwilioSignature(token,url); const req=new Request(url,{method:'POST',headers:{'Content-Type':'application/json','X-Twilio-Signature':sig},body:raw}); assert.equal(await verifyTwilioRequest(req,raw,token),true); assert.equal(await verifyTwilioRequest(req,'{"CallSid":"changed"}',token),false)})
test('handler returns generic 403 for invalid signature and only best-effort KV telemetry',async()=>{const kv={values:new Map<string,string>(),async get(k:string){return this.values.get(k)??null},async put(k:string,v:string){this.values.set(k,v)}}; const req=new Request('https://voice.example.com/webhook/twilio/voice',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'CallSid=CA123'}); const res=await handleTwilioWebhook(req,{TWILIO_AUTH_TOKEN:token,CAROLINE_PHONE:kv as any,ENVIRONMENT:'development'},'r'); assert.equal(res.status,403); assert.deepEqual(await res.json(),{error:'forbidden'}); assert.equal(kv.values.size,1)})
