import { createClient } from '@supabase/supabase-js'
const H={'Content-Type':'application/json','Cache-Control':'no-store'}
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H})
const U=Deno.env.get('SUPABASE_URL')!,SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,RK=Deno.env.get('CAROLINE_RUNTIME_KEY'),db=createClient(U,SK)
const str=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null
function auth(r:Request){return !!RK&&r.headers.get('x-caroline-key')===RK}
function iso(v:unknown):string|null|'invalid'{if(v==null||v==='')return null;if(typeof v!=='string')return'invalid';const n=Date.parse(v);return Number.isFinite(n)?new Date(n).toISOString():'invalid'}
async function cfg(k:string){const{data}=await db.from('caroline_integration_config').select('value').eq('key',k).maybeSingle();return str(data?.value)}
async function owner(b:any){const expected=await cfg('telegram_owner_chat_id'),supplied=str(b?.owner_chat_id);return !!expected&&supplied===expected}
async function prior(id:string){const{data}=await db.from('events_processed').select('event_id,details').eq('event_id',id).maybeSingle();return data??null}
Deno.serve(async r=>{if(!auth(r))return J({error:'unauthorized'},401);if(r.method!=='POST')return J({error:'method_not_allowed'},405);let b:any;try{b=await r.json()}catch{return J({error:'invalid_json'},400)};if(!await owner(b))return J({error:'owner_not_authorized'},403);const status=str(b?.status),human=str(b?.human_readable),rid=str(b?.request_id),tz=str(b?.timezone)??'America/New_York',from=iso(b?.available_from),until=iso(b?.available_until);if(!status||!['available','unavailable','busy','unknown'].includes(status))return J({error:'invalid_status'},400);if(!human)return J({error:'human_readable_required'},400);if(from==='invalid'||until==='invalid')return J({error:'invalid_availability_time'},400);if(from&&until&&Date.parse(from)>=Date.parse(until))return J({error:'availability_window_invalid'},400);if(!rid)return J({error:'request_id_required'},400);const eid=`telegram:availability:${rid}`;if(await prior(eid))return J({ok:true,duplicate:true,status,human_readable:human,available_from:from,available_until:until,timezone:tz});const{error}=await db.from('availability_state').upsert({id:true,status,human_readable:human,available_from:from,available_until:until,timezone:tz,updated_by:'telegram_owner',updated_at:new Date().toISOString()},{onConflict:'id'});if(error)return J({error:'availability_update_failed'},500);await db.from('events_processed').insert({event_id:eid,event_type:'owner_availability_updated',details:{status,human_readable:human,available_from:from,available_until:until,timezone:tz},telegram_notification_status:'skipped'});return J({ok:true,duplicate:false,status,human_readable:human,available_from:from,available_until:until,timezone:tz})})

