import { createClient } from '@supabase/supabase-js'
const H={'Content-Type':'application/json','Cache-Control':'no-store'}
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H})
const U=Deno.env.get('SUPABASE_URL')!,SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const db=createClient(U,SK)
const supported=new Set(['contacts','call_history','instructions','availability_state'])
const clean=(v:any)=>v===undefined?null:v
async function cfg(keys:string[]){const{data,error}=await db.from('caroline_integration_config').select('key,value').in('key',keys);if(error)return{} as Record<string,string>;return Object.fromEntries((data??[]).map((x:any)=>[x.key,x.value])) as Record<string,string>}
async function source(t:string,id:string){if(t==='availability_state'){const{data,error}=await db.from(t).select('*').eq('id',true).maybeSingle();return{data,error}}const{data,error}=await db.from(t).select('*').eq('id',id).maybeSingle();return{data,error}}
function payload(t:string,id:string,r:any){const b:any={source_table:t,source_id:id};if(t==='contacts')return{...b,display_name:clean(r.display_name),normalized_phone:clean(r.normalized_phone),relationship_to_owner:clean(r.relationship_to_owner),contact_type:clean(r.contact_type),verification_status:clean(r.verification_status),tone_profile:clean(r.tone_profile),notes:clean(r.notes)};if(t==='call_history')return{...b,conversation_id:clean(r.conversation_id),caller_name:clean(r.caller_name),normalized_phone:clean(r.normalized_phone),caller_organization:clean(r.caller_organization),request_summary:clean(r.request_summary),request_urgency:clean(r.request_urgency),call_outcome:clean(r.call_outcome),direction:clean(r.direction),started_at:clean(r.started_at),call_duration_secs:clean(r.call_duration_secs)};if(t==='instructions')return{...b,instruction:clean(r.instruction),scope_type:clean(r.scope_type),status:clean(r.status),durable:r.durable===true,active_until:clean(r.active_until)};if(t==='availability_state')return{...b,human_readable:clean(r.human_readable),status:clean(r.status),available_from:clean(r.available_from),available_until:clean(r.available_until)};return null}
async function mark(t:string,id:string,status:string,error:string|null=null){const{data:old}=await db.from('airtable_sync_jobs').select('attempts').eq('source_table',t).eq('source_id',id).maybeSingle();const attempts=status==='waiting_activation'?Number(old?.attempts??0):Number(old?.attempts??0)+1;const row:any={source_table:t,source_id:id,status,attempts,last_error:error,last_attempted_at:new Date().toISOString()};if(status==='dispatched')row.last_dispatched_at=new Date().toISOString();await db.from('airtable_sync_jobs').upsert(row,{onConflict:'source_table,source_id'})}
async function syncOne(t:string,id:string){if(!supported.has(t))return{ok:false,error:'unsupported_source_table'};const c=await cfg(['airtable_mirror_webhook_url','airtable_mirror_enabled']);const url=c.airtable_mirror_webhook_url,enabled=c.airtable_mirror_enabled==='true';if(!url||!enabled){await mark(t,id,'waiting_activation','airtable_automation_not_enabled');return{ok:false,error:'airtable_automation_not_enabled'}};const s=await source(t,id);if(s.error){await mark(t,id,'failed','source_read_failed');return{ok:false,error:'source_read_failed'}};if(!s.data){await mark(t,id,'failed','source_not_found');return{ok:false,error:'source_not_found'}};const p=payload(t,id,s.data);if(!p){await mark(t,id,'failed','mapping_failed');return{ok:false,error:'mapping_failed'}};let r:Response;try{r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)})}catch{await mark(t,id,'failed','airtable_webhook_unreachable');return{ok:false,error:'airtable_webhook_unreachable'}};if(!r.ok){await mark(t,id,'failed',`airtable_webhook_http_${r.status}`);return{ok:false,error:`airtable_webhook_http_${r.status}`}};await mark(t,id,'dispatched',null);return{ok:true,dispatched:true}}
async function drain(limit=20){const{data,error}=await db.from('airtable_sync_jobs').select('source_table,source_id').in('status',['pending','failed','waiting_activation']).order('last_enqueued_at',{ascending:true}).limit(Math.max(1,Math.min(50,limit)));if(error)return{ok:false,error:'queue_read_failed'};const out=[];for(const j of data??[])out.push({source_table:j.source_table,source_id:j.source_id,...await syncOne(j.source_table,j.source_id)});return{ok:true,attempted:out.length,results:out}}
Deno.serve(async req=>{if(req.method!=='POST')return J({error:'method_not_allowed'},405);let b:any={};try{b=await req.json()}catch{};if(b?.drain===true)return J(await drain(Number(b?.limit)||20));const t=typeof b?.source_table==='string'?b.source_table:'',id=typeof b?.source_id==='string'?b.source_id:'';if(!t||!id)return J({error:'source_table_and_source_id_required'},400);const out=await syncOne(t,id);return J(out,out.ok?200:(out.error==='airtable_automation_not_enabled'?503:502))})

