import { createClient } from '@supabase/supabase-js'
const H={'Content-Type':'application/json','Cache-Control':'no-store'}
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H})
const U=Deno.env.get('SUPABASE_URL')!,SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,RK=Deno.env.get('CAROLINE_RUNTIME_KEY'),db=createClient(U,SK)
const str=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null
function auth(r:Request){return !!RK&&r.headers.get('x-caroline-key')===RK}
function phone(v:unknown){const r=str(v);if(!r)return null;const d=r.replace(/\D/g,'');let c='';if(r.startsWith('+'))c=`+${d}`;else if(d.length===10)c=`+1${d}`;else if(d.length===11&&d.startsWith('1'))c=`+${d}`;else c=`+${d}`;return /^\+[1-9]\d{7,14}$/.test(c)?c:null}
function lim(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.max(1,Math.min(10,Math.trunc(n))):5}
async function owner(body:any){const supplied=str(body?.owner_chat_id);const{data}=await db.from('caroline_integration_config').select('value').eq('key','telegram_owner_chat_id').maybeSingle();const expected=str(data?.value);return !!expected&&supplied===expected}
Deno.serve(async r=>{if(!auth(r))return J({error:'unauthorized'},401);if(r.method!=='POST')return J({error:'method_not_allowed'},405);let b:any;try{b=await r.json()}catch{return J({error:'invalid_json'},400)};if(!await owner(b))return J({error:'owner_not_authorized'},403);const conversationId=str(b?.conversation_id),rawPhone=str(b?.phone),p=rawPhone?phone(rawPhone):null;if(rawPhone&&!p)return J({error:'invalid_phone'},400);const limit=lim(b?.limit),includeTranscript=b?.include_transcript===true,includeEvents=b?.include_events===true;const fields=includeTranscript?'conversation_id,normalized_phone,caller_name,caller_organization,caller_relationship,request_summary,request_urgency,call_outcome,callback_number,detected_tone_profile,relationship_context_and_notes,started_at,ended_at,created_at,telephony_provider,direction,provider_call_id,agent_phone_number_id,call_duration_secs,termination_reason,call_successful,transcript,telegram_notification_status,telegram_message_id,telegram_notified_at':'conversation_id,normalized_phone,caller_name,caller_organization,caller_relationship,request_summary,request_urgency,call_outcome,callback_number,detected_tone_profile,relationship_context_and_notes,started_at,ended_at,created_at,telephony_provider,direction,provider_call_id,agent_phone_number_id,call_duration_secs,termination_reason,call_successful,telegram_notification_status,telegram_message_id,telegram_notified_at';let q=db.from('call_history').select(fields);if(conversationId)q=q.eq('conversation_id',conversationId);else if(p)q=q.eq('normalized_phone',p);q=q.order('created_at',{ascending:false}).limit(limit);const{data:calls,error:ce}=await q;if(ce)return J({error:'call_log_read_failed'},500);let events:any[]=[];if(includeEvents){let eq=db.from('events_processed').select('event_id,event_type,conversation_id,processed_at,details,telegram_notification_status,telegram_message_id,telegram_notified_at').order('processed_at',{ascending:false}).limit(Math.max(limit*10,50));if(conversationId)eq=eq.eq('conversation_id',conversationId);const{data:raw,error:ee}=await eq;if(ee)return J({error:'event_log_read_failed'},500);const ids=new Set((calls??[]).map((x:any)=>x.conversation_id).filter(Boolean));events=(raw??[]).filter((e:any)=>{if(conversationId)return e.conversation_id===conversationId;if(!p)return true;const d=e?.details??{};return (e.conversation_id&&ids.has(e.conversation_id))||[d.to_number,d.normalized_phone,d.phone,d.callback_number].some(x=>phone(x)===p)}).slice(0,limit)}const safe=(calls??[]).map((x:any)=>({...x,transcript_available:includeTranscript?Array.isArray(x.transcript)&&x.transcript.length>0:undefined}));return J({ok:true,calls:safe,events})})

