import { createClient } from '@supabase/supabase-js'
const headers={'Content-Type':'application/json','Cache-Control':'no-store'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers})
const supabaseUrl=Deno.env.get('SUPABASE_URL')!,serviceRoleKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,runtimeKey=Deno.env.get('CAROLINE_RUNTIME_KEY'),notifyUrl=`${supabaseUrl}/functions/v1/caroline-notify`,db=createClient(supabaseUrl,serviceRoleKey)
function authorized(req:Request){return !!runtimeKey&&req.headers.get('x-caroline-key')===runtimeKey}
function safeString(v:unknown){return typeof v==='string'&&v.trim()?v.trim():null}
async function ownerTelegramChatId(){const{data}=await db.from('caroline_integration_config').select('value').eq('key','telegram_owner_chat_id').maybeSingle();return safeString(data?.value)}
async function ownerAuthorized(body:any){const supplied=safeString(body?.owner_chat_id),expected=await ownerTelegramChatId();return !!expected&&!!supplied&&supplied===expected}
function boundedLimit(v:unknown){const n=Number(v);return Number.isFinite(n)?Math.max(1,Math.min(10,Math.trunc(n))):5}
async function notify(target:any){try{const r=await fetch(notifyUrl,{method:'POST',headers:{'Content-Type':'application/json','x-caroline-key':runtimeKey!},body:JSON.stringify(target)}),t=await r.text();let b:any=null;try{b=t?JSON.parse(t):null}catch{}return r.ok?{ok:true,body:b}:{ok:false,error:b?.error??`notify_http_${r.status}`}}catch{return{ok:false,error:'notify_request_failed'}}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers});if(!authorized(req))return json({error:'unauthorized'},401);if(req.method!=='POST')return json({error:'method_not_allowed'},405);let body:any;try{body=await req.json()}catch{return json({error:'invalid_json'},400)}if(!await ownerAuthorized(body))return json({error:'owner_not_authorized'},403);const conversationId=safeString(body?.conversation_id),eventId=safeString(body?.event_id);if(conversationId){const result=await notify({conversation_id:conversationId});return result.ok?json({ok:true,target:'conversation',conversation_id:conversationId,result:result.body}):json({error:result.error},502)}if(eventId){const result=await notify({event_id:eventId});return result.ok?json({ok:true,target:'event',event_id:eventId,result:result.body}):json({error:result.error},502)}const limit=boundedLimit(body?.limit),[calls,events]=await Promise.all([db.from('call_history').select('conversation_id,telegram_notification_status').in('telegram_notification_status',['pending','failed']).not('conversation_id','is',null).order('created_at',{ascending:false}).limit(limit),db.from('events_processed').select('event_id,telegram_notification_status').in('telegram_notification_status',['pending','failed']).order('processed_at',{ascending:false}).limit(limit)]);if(calls.error||events.error)return json({error:'notification_retry_lookup_failed'},500);const results:any[]=[];for(const row of calls.data??[]){const r=await notify({conversation_id:row.conversation_id});results.push({type:'call',id:row.conversation_id,ok:r.ok,error:r.ok?null:r.error})}for(const row of events.data??[]){const r=await notify({event_id:row.event_id});results.push({type:'event',id:row.event_id,ok:r.ok,error:r.ok?null:r.error})}return json({ok:true,attempted:results.length,results})})

