import { createClient } from '@supabase/supabase-js'
const U=Deno.env.get('SUPABASE_URL')!,SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,RK=Deno.env.get('CAROLINE_RUNTIME_KEY'),SID=Deno.env.get('TWILIO_ACCOUNT_SID'),TW=Deno.env.get('TWILIO_AUTH_TOKEN'),db=createClient(U,SK)
const H={'Content-Type':'application/json','Cache-Control':'no-store'},J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H})
const str=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null
function phone(v:unknown){const r=str(v);if(!r)return null;const d=r.replace(/\D/g,'');let c='';if(r.startsWith('+'))c='+'+d;else if(d.length===10)c='+1'+d;else if(d.length===11&&d.startsWith('1'))c='+'+d;else c='+'+d;return /^\+[1-9]\d{7,14}$/.test(c)?c:null}
function iso(v:unknown){const s=str(v);if(!s)return null;const d=new Date(s);return Number.isNaN(d.getTime())?null:d.toISOString()}
async function cfg(k:string){const{data}=await db.from('caroline_integration_config').select('value').eq('key',k).maybeSingle();return str(data?.value)}
async function ownerPhones(){const out=new Set<string>();const multi=await cfg('owner_phone_numbers');if(multi){try{const a=JSON.parse(multi);if(Array.isArray(a))for(const v of a){const n=phone(v);if(n)out.add(n)}}catch{}}const legacy=phone(await cfg('owner_phone_number'));if(legacy)out.add(legacy);return out}
function runtime(req:Request){return !!RK&&req.headers.get('x-caroline-key')===RK}
function extUrl(req:Request){const u=new URL(req.url),host=req.headers.get('x-forwarded-host')||req.headers.get('host')||u.host,proto=(req.headers.get('x-forwarded-proto')||u.protocol.replace(':',''));return proto+'://'+host+u.pathname+u.search}
async function validTwilio(req:Request,params:URLSearchParams){if(!TW)return false;const sig=str(req.headers.get('x-twilio-signature'));if(!sig)return false;let base=extUrl(req);const pairs=[...params.entries()].sort((a,b)=>a[0].localeCompare(b[0]));for(const [k,v] of pairs)base+=k+v;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(TW),{name:'HMAC',hash:'SHA-1'},false,['sign']);const raw=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(base)));let bin='';for(const b of raw)bin+=String.fromCharCode(b);const expected=btoa(bin);if(expected.length!==sig.length)return false;let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^sig.charCodeAt(i);return diff===0}
async function ownerOk(b:any){if(b?.internal_scheduled_action===true)return true;const [chat,owners]=await Promise.all([cfg('telegram_owner_chat_id'),ownerPhones()]);const suppliedChat=str(b?.owner_chat_id),suppliedPhone=phone(b?.owner_phone);return (!!chat&&suppliedChat===chat)||(!!suppliedPhone&&owners.has(suppliedPhone))}
function finalBody(summary:string){const core=summary.replace(/^\s*(hi|hello)[,]?\s*/i,'').trim();return ("Hi, this is Caroline, Chris's assistant. "+core+" For any reply, please call or text Chris directly at (609) 517-4517.").replace(/\s+/g,' ').trim()}
async function notifySms(id:string,kind:string){if(!RK)return;await fetch(U+'/functions/v1/caroline-notify',{method:'POST',headers:{'Content-Type':'application/json','x-caroline-key':RK},body:JSON.stringify({sms_history_id:id,notification_kind:kind})}).catch(()=>{})}
async function notifyDelivered(row:any){if(!RK)return;const eid='sms_delivered:'+row.provider_message_id;await db.from('events_processed').upsert({event_id:eid,event_type:'sms_delivered',details:{normalized_phone:row.normalized_phone,provider_message_id:row.provider_message_id,delivered_at:row.delivered_at},telegram_notification_status:'pending'},{onConflict:'event_id',ignoreDuplicates:true});await fetch(U+'/functions/v1/caroline-notify',{method:'POST',headers:{'Content-Type':'application/json','x-caroline-key':RK},body:JSON.stringify({event_id:eid})}).catch(()=>{})}
async function scheduleSms(b:any,to:string,summary:string,requestId:string){if(!RK)return J({result_code:'RETRYABLE_PROVIDER_ERROR',error:'runtime_key_not_configured'},503);const executeAt=iso(b?.execute_at);if(!executeAt)return J({result_code:'MISSING_REQUIRED_DETAIL',error:'invalid_execute_at',missing_fields:['execute_at']},400);if(Date.parse(executeAt)<=Date.now()-60000)return J({result_code:'MISSING_REQUIRED_DETAIL',error:'execute_at_in_past',missing_fields:['execute_at']},400);let resp:Response,body:any=null;try{resp=await fetch(U+'/functions/v1/caroline-sms-actions/schedule',{method:'POST',headers:{'Content-Type':'application/json','x-caroline-key':RK},body:JSON.stringify({owner_chat_id:str(b?.owner_chat_id),owner_phone:phone(b?.owner_phone),conversation_id:str(b?.conversation_id),agent_turn:Number.isFinite(Number(b?.agent_turn))?Number(b.agent_turn):undefined,request_id:requestId,target_phone:to,execute_at:executeAt,timezone:str(b?.timezone)??'America/New_York',linked_call_history_id:str(b?.linked_call_history_id),message_summary:summary,original_instruction:str(b?.original_instruction)})});const tx=await resp.text();try{body=tx?JSON.parse(tx):null}catch{body=null}}catch{return J({result_code:'RETRYABLE_PROVIDER_ERROR',error:'schedule_request_failed'},502)}
if(!resp.ok){const err=str(body?.error)??'schedule_failed';const code=resp.status===403?'NOT_OWNER':resp.status===404?'NOT_FOUND':resp.status===409?'ACCESS_DENIED':resp.status>=500?'RETRYABLE_PROVIDER_ERROR':'MISSING_REQUIRED_DETAIL';return J({result_code:code,error:err},resp.status)}
const action=body?.scheduled_action??null;return J({result_code:'SCHEDULED',ok:true,scheduled:true,duplicate:!!body?.duplicate,scheduled_action_id:action?.id??null,calendar_event_id:body?.calendar_event?.id??null,target:body?.target??null,scheduled_action:action},resp.status===201?201:200)}
async function sendSms(req:Request,b:any){if(!runtime(req))return J({result_code:'NOT_OWNER',error:'unauthorized'},401);if(!await ownerOk(b))return J({result_code:'NOT_OWNER',error:'owner_not_authorized'},403);const to=phone(b?.to_number),summary=str(b?.message_summary),requestId=str(b?.request_id)??(str(b?.conversation_id)&&Number.isFinite(Number(b?.agent_turn))?str(b.conversation_id)+':'+String(Number(b.agent_turn)):null);if(!to||!summary||!requestId){const missing=[];if(!to)missing.push('to_number');if(!summary)missing.push('message_summary');if(!requestId)missing.push('request_identity');return J({result_code:'MISSING_REQUIRED_DETAIL',error:'to_number_message_summary_request_identity_required',missing_fields:missing},400)}
if(str(b?.execute_at)&&b?.internal_scheduled_action!==true)return await scheduleSms(b,to,summary,requestId)
if(b?.internal_test_dry_run===true)return J({result_code:'OK',ok:true,dry_run:true,to_number:to,rendered_body:finalBody(summary)});if(!SID||!TW)return J({result_code:'RETRYABLE_PROVIDER_ERROR',error:'twilio_messaging_not_configured'},503);const from=phone(await cfg('twilio_phone_number'));if(!from)return J({result_code:'RETRYABLE_PROVIDER_ERROR',error:'twilio_phone_number_not_configured'},503);const eventId=(b?.internal_scheduled_action===true?'scheduled':'owner')+':outbound_sms:'+requestId;const{data:prior}=await db.from('events_processed').select('details').eq('event_id',eventId).maybeSingle();if(prior){const d:any=prior.details??{};return J({result_code:'DUPLICATE_PREVENTED',ok:d.state==='sent',duplicate:true,sms_history_id:d.sms_history_id??null,provider_message_id:d.provider_message_id??null})}
const body=finalBody(summary);const linked=str(b?.linked_call_history_id);let contactId:any=null;if(str(b?.target_contact_id))contactId=str(b.target_contact_id);else{const{data:c}=await db.from('contacts').select('id').eq('normalized_phone',to).maybeSingle();contactId=c?.id??null}
const{data:reserved,error:re}=await db.from('sms_history').insert({normalized_phone:to,contact_id:contactId,direction:'outbound',body,status:'creating',linked_call_history_id:linked,telegram_notification_status:'pending'}).select('id').single();if(re)return J({result_code:'RETRYABLE_PROVIDER_ERROR',error:'sms_history_reservation_failed'},500)
await db.from('events_processed').insert({event_id:eventId,event_type:'outbound_sms_reserved',details:{state:'reserved',sms_history_id:reserved.id,to_number:to},telegram_notification_status:'skipped'})
const form=new URLSearchParams({To:to,From:from,Body:body,StatusCallback:U+'/functions/v1/caroline-sms/status-callback'});let resp:Response,j:any=null;try{resp=await fetch('https://api.twilio.com/2010-04-01/Accounts/'+SID+'/Messages.json',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Authorization':'Basic '+btoa(SID+':'+TW)},body:form.toString()});const tx=await resp.text();try{j=tx?JSON.parse(tx):null}catch{}}catch{await db.from('sms_history').update({status:'failed'}).eq('id',reserved.id);return J({result_code:'RETRYABLE_PROVIDER_ERROR',error:'twilio_send_failed'},502)}
if(!resp.ok||!str(j?.sid)){await db.from('sms_history').update({status:'failed'}).eq('id',reserved.id);await db.from('events_processed').update({event_type:'outbound_sms_failed',details:{state:'failed',sms_history_id:reserved.id,error:'twilio_http_'+resp.status}}).eq('event_id',eventId);return J({result_code:'RETRYABLE_PROVIDER_ERROR',error:'twilio_send_failed',upstream_status:resp.status},502)}
const now=new Date().toISOString(),provider=str(j.sid)!;await db.from('sms_history').update({provider_message_id:provider,status:str(j.status)??'queued',sent_at:now}).eq('id',reserved.id);await db.from('events_processed').update({event_type:'outbound_sms_sent',details:{state:'sent',sms_history_id:reserved.id,provider_message_id:provider,to_number:to}}).eq('event_id',eventId);EdgeRuntime.waitUntil(notifySms(reserved.id,'sent'));return J({result_code:'OK',ok:true,sent:true,sms_history_id:reserved.id,provider_message_id:provider,status:str(j.status)??'queued',sent_at:now})}
async function statusCb(req:Request){const raw=await req.text(),p=new URLSearchParams(raw);if(!await validTwilio(req,p))return J({error:'invalid_twilio_signature'},403);const sid=str(p.get('MessageSid')),status=str(p.get('MessageStatus')||p.get('SmsStatus'));if(!sid||!status)return J({error:'message_sid_and_status_required'},400);const{data:row}=await db.from('sms_history').select('*').eq('provider_message_id',sid).maybeSingle();if(!row)return J({ok:true,ignored:true});const patch:any={status};if(status==='delivered'&&!row.delivered_at)patch.delivered_at=new Date().toISOString();const{data:updated,error}=await db.from('sms_history').update(patch).eq('id',row.id).select('*').single();if(error)return J({error:'sms_status_update_failed'},500);const suppressNotify=!!RK&&req.headers.get('x-caroline-key')===RK&&req.headers.get('x-caroline-regression-no-notify')==='true';if(status==='delivered'&&!row.delivered_at&&!suppressNotify)EdgeRuntime.waitUntil(notifyDelivered(updated));return J({ok:true,status,delivered_at:updated.delivered_at??null})}
Deno.serve(async req=>{const path=new URL(req.url).pathname;if(path.endsWith('/status-callback'))return await statusCb(req);if(path.endsWith('/send')){let b:any={};try{b=await req.json()}catch{return J({result_code:'MISSING_REQUIRED_DETAIL',error:'invalid_json'},400)}return await sendSms(req,b)}return J({error:'not_found'},404)})

